apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ee86257ed-python
  janus-idp.io/tekton: ee86257ed-python
  backstage.io/kubernetes-id: ee86257ed-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ee86257ed-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
